#!/bin/bash

# change the file seperator so that the output of the find command doesn't seperate when it finds a space in a filename
IFS=$(echo -en "\n\b")

# Loop through all files in current dir and subdirs ending in ".pdf"
for f in $(find . -type f -iname '*.pdf' ); do

	declare -i infilesize
	declare -i outfilesize


# set the name of the input pdf file 
in=$f

# Determine output filename
# remove bits that aren't filename
   outfile=$(basename $f)

# replace spaces with underscores in the output filename
   outfile=${outfile// /_}

# set output directory
outpath="/Volumes/Thumper/Temp/aciar_node_pdf/"
# write out the whole path and filename for the output file
   out=$outpath$outfile
   #echo ${f##*/}

infilesize=$(du -k $in | cut -f1);
infilesizehr=$(du -h $in | cut -f1);
outfilesize=$(du -k $out | cut -f1);
outfilesizehr=$(du -h $out | cut -f1);

# echo  $infilesizehr


 if [ "$infilesize" -gt "$outfilesize" ]
  then

  infiletotal=$(($infiletotal+infilesize))
  outfiletotal=$(($outfiletotal+outfilesize))
  difference=$(($infiletotal-outfiletotal))
  
 	#statements
 	# echo $outfile "Win!" $infilesizehr " now " $outfilesizehr
else
 	echo $outfile "Lose " $infilesizehr " now " $outfilesizehr
 fi  

done

 echo "difference" $difference



